<?php

/**
 * @file
 * Functions to support the DKAN frontend.
 */

/**
 * Implements hook_page_attachments_alter().
 */
function dkan_js_frontend_bartik_page_attachments_alter(array &$attachments) {
  if (\Drupal::routeMatch()->getRouteObject()->getDefault('name') != 'dkan_js_frontend') {
    return;
  }
  if (($key = array_search('bartik/global-styling', $attachments['#attached']['library'])) !== FALSE) {
    unset($attachments['#attached']['library'][$key]);
  }

}
