<?php

/**
 * @file
 * Functions to support the DKAN frontend.
 */

/**
 * Implements hook_page_attachments_alter().
 */
function bartik_page_attachments_alter(array &$attachments) {
  $request = \Drupal::routeMatch()->getRouteObject()->getDefault('name');
  if ($request == 'dkan_js_frontend') {
    foreach ($attachments['#attached']['library'] as $key => $library) {
      if ($library == 'bartik/global-styling') {
        unset($attachments['#attached']['library'][$key]);
      }
    }
  }

}
